/* Generated by scripts/build-tokens.mjs from tokens/*.tokens.json (DTCG).
Do not edit by hand: change the source tokens and run `npm run tokens:build`. */

export const tokens = {
  "color": {
    "bg": "#f9fafb",
    "surface": "#ffffff",
    "text": "#111827",
    "text-muted": "#4b5563",
    "accent": "#2563eb",
    "accent-strong": "#1e40af",
    "accent-soft": "#dbeafe",
    "on-accent": "#ffffff",
    "success": "#15803d",
    "success-strong": "#166534",
    "success-soft": "#dcfce7",
    "warning": "#b45309",
    "warning-strong": "#92400e",
    "warning-soft": "#fef3c7",
    "danger": "#dc2626",
    "danger-strong": "#991b1b",
    "danger-soft": "#fee2e2",
    "neutral-soft": "#f3f4f6",
    "border": "#d1d5db",
    "border-strong": "#9ca3af",
    "focus-ring": "#2563eb",
    "overlay": "rgba(17, 24, 39, 0.55)"
  },
  "radius": {
    "sm": "4px",
    "md": "6px",
    "lg": "10px",
    "full": "9999px"
  },
  "space": {
    "2xs": "0.25rem",
    "xs": "0.5rem",
    "sm": "0.75rem",
    "md": "1rem",
    "lg": "1.5rem",
    "xl": "2rem"
  },
  "typography": {
    "fontFamily": {
      "sans": "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
      "mono": "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
    },
    "fontSize": {
      "xs": "0.75rem",
      "sm": "0.875rem",
      "md": "1rem",
      "lg": "1.125rem"
    },
    "lineHeight": {
      "tight": 1.25,
      "normal": 1.5
    },
    "fontWeight": {
      "regular": 400,
      "medium": 500,
      "semibold": 600
    }
  }
} as const;

export type Tokens = typeof tokens;
