/**
 * DTCG token compiler of the Small UIKit (T-042, ADR-014).
 *
 * Source of truth: tokens/*.tokens.json in the Design Tokens Community Group
 * format (groups carry `$type`, leaves carry `$value`). This script is
 * dependency-free Node: it emits `src/tokens.css` (CSS custom properties
 * `--small-*`) and `src/tokens.ts` (typed const). Both generated files are
 * committed; `tests/tokens.test.ts` regenerates them in memory and fails on
 * drift, so a hand edit of a generated file cannot pass CI.
 *
 * Usage: `npm run tokens:build` (or `node scripts/build-tokens.mjs`).
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TOKENS_DIR = join(ROOT, "tokens");

/**
 * Load and validate every `tokens/*.tokens.json` file.
 * @returns {{ name: string, data: Record<string, unknown> }[]}
 */
export function loadTokenFiles() {
  const names = readdirSync(TOKENS_DIR)
    .filter((name) => name.endsWith(".tokens.json"))
    .sort();
  if (names.length === 0) {
    throw new Error(`no *.tokens.json files found in ${TOKENS_DIR}`);
  }
  return names.map((name) => {
    const data = JSON.parse(readFileSync(join(TOKENS_DIR, name), "utf8"));
    walk(data, undefined, [], name);
    return { name, data };
  });
}

/**
 * Validate a DTCG tree: every leaf carries `$value` (string|number) and a
 * resolvable `$type` (own or inherited from the nearest group); only `$`-meta
 * keys are allowed besides that.
 * @param {Record<string, unknown>} node current group
 * @param {string | undefined} inheritedType $type inherited from parent group
 * @param {string[]} path path of group keys so far
 * @param {string} file source file name for error messages
 */
function walk(node, inheritedType, path, file) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const here = [...path, key].join(".");
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      throw new Error(`${file}: ${here} must be a DTCG group or token object`);
    }
    const record = /** @type {Record<string, unknown>} */ (value);
    const type = typeof record.$type === "string" ? record.$type : inheritedType;
    if (record.$value !== undefined) {
      if (type === undefined) {
        throw new Error(
          `${file}: ${here} has no resolvable $type (declare $type on the token or on a parent group)`,
        );
      }
      if (typeof record.$value !== "string" && typeof record.$value !== "number") {
        throw new Error(`${file}: ${here}.$value must be a string or a number`);
      }
      for (const meta of Object.keys(record)) {
        if (meta !== "$value" && meta !== "$type" && meta !== "$description") {
          throw new Error(`${file}: ${here} has unexpected key ${meta}`);
        }
      }
    } else {
      // A group's non-$ keys are its children; only the $-meta keys need checking.
      for (const meta of Object.keys(record)) {
        if (meta.startsWith("$") && meta !== "$type" && meta !== "$description") {
          throw new Error(`${file}: group ${here} has unexpected meta key ${meta}`);
        }
      }
      walk(record, type, [...path, key], file);
    }
  }
}

/**
 * Flatten a DTCG tree into `[cssVarName, value]` pairs.
 * @param {Record<string, unknown>} data parsed DTCG file
 * @returns {[string, string | number][]}
 */
function flatten(data) {
  const out = [];
  const visit = (node, path) => {
    for (const [key, value] of Object.entries(node)) {
      if (key.startsWith("$")) continue;
      const record = /** @type {Record<string, unknown>} */ (value);
      if (record.$value !== undefined) {
        out.push([kebab([...path, key].join("-")), record.$value]);
      } else {
        visit(record, [...path, key]);
      }
    }
  };
  visit(data, []);
  return out;
}

/** camelCase path segment -> kebab-case (for CSS custom property names). */
function kebab(key) {
  return key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

const HEADER =
  "Generated by scripts/build-tokens.mjs from tokens/*.tokens.json (DTCG).\n" +
  "Do not edit by hand: change the source tokens and run `npm run tokens:build`.";

/**
 * Render the generated files' contents in memory (also used by the drift test).
 * @param {{ name: string, data: Record<string, unknown> }[]} files
 * @returns {{ css: string, ts: string }}
 */
export function generate(files) {
  const cssLines = [`/* ${HEADER} */`, "", ":root {"];
  const tsTree = {};
  for (const { name, data } of files) {
    cssLines.push(`  /* ${name} */`);
    for (const [varName, value] of flatten(data)) {
      cssLines.push(`  --small-${varName}: ${value};`);
    }
    mergeTree(tsTree, name, data);
  }
  cssLines.push("}", "");
  const css = cssLines.join("\n");
  const ts = `/* ${HEADER} */\n\nexport const tokens = ${JSON.stringify(tsTree, null, 2)} as const;\n\nexport type Tokens = typeof tokens;\n`;
  return { css, ts };
}

/**
 * Merge one DTCG file into the nested TS token tree.
 * @param {Record<string, unknown>} tree target tree
 * @param {string} name file name (used for error messages only)
 * @param {Record<string, unknown>} data parsed DTCG file
 */
function mergeTree(tree, name, data) {
  for (const [group, value] of Object.entries(data)) {
    if (tree[group] !== undefined) {
      throw new Error(`${name}: top-level group ${group} duplicates another token file`);
    }
    const nested = prune(value);
    if (nested === undefined) {
      throw new Error(`${name}: group ${group} contains no tokens`);
    }
    tree[group] = nested;
  }
}

/** @returns {Record<string, unknown> | string | number | undefined} */
function prune(node) {
  if (typeof node !== "object" || node === null) return undefined;
  const record = /** @type {Record<string, unknown>} */ (node);
  if (record.$value !== undefined) return record.$value;
  const out = {};
  let count = 0;
  for (const [key, value] of Object.entries(record)) {
    if (key.startsWith("$")) continue;
    const pruned = prune(value);
    if (pruned === undefined) {
      throw new Error(`empty group ${key} cannot be represented in tokens.ts`);
    }
    out[key] = pruned;
    count += 1;
  }
  if (count === 0) return undefined;
  return out;
}

const files = loadTokenFiles();
const { css, ts } = generate(files);
// CLI guard: importing this module (e.g. from the drift test) must NOT rewrite
// the generated files — the gate compares an in-memory run against what is
// committed. Only a direct `node scripts/build-tokens.mjs` run writes.
const invokedDirectly =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  writeFileSync(join(ROOT, "src", "tokens.css"), css);
  writeFileSync(join(ROOT, "src", "tokens.ts"), ts);
  console.log(`tokens: wrote src/tokens.css and src/tokens.ts from ${files.length} DTCG file(s)`);
}
